# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'testwcdb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod  'WCDB','1.0.7.5'
  
  # Pods for testwcdb

end
